## Outcome of Symmetry Operations:
<br>

| 1D Object | Identity | Inversion | Mirror_z | Mirror_y | Rotation_180 |
|-----------|----------|-----------|----------|----------|--------------|
|Scalar | 1 | Even | Even | Even | Even |
|
|Pseudoscalar | 1 | Odd | Even | Even| Even|
|
|Polar Vector | 1 |Even|Even|Odd|Odd
|
|Axial Vector | 1 |Even|Even|Odd|Odd





In [118]:
#Defining Operations

Inversion = inv = np.array([[-1, 0, 0], [0, -1, 0], [0, 0, -1]])

Mirror_z = mirZ = np.array([[-1, 0, 0], [0, -1, 0], [0, 0, 1]])

Mirror_x = mirX = np.array([[1, 0, 0], [0, -1, 0], [0, 0, -1]])

#Rotation of 180 about x axis... wouldn't this be the same as mirror_x? assuming about y axis? maybe too tired.

rot180 = np.array([[-1, 0, 0], [0, 1, 0], [0, 0, -1]])

print("Inversion:")
print(inv)
print("Mirror_Z:")
print(mirZ)
print("Mirror_X:")
print(mirX)
print("Rotation_Y(?)")
print(rot180)


Inversion:
[[-1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
Mirror_Z:
[[-1  0  0]
 [ 0 -1  0]
 [ 0  0  1]]
Mirror_X:
[[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
Rotation_Y(?)
[[-1  0  0]
 [ 0  1  0]
 [ 0  0 -1]]


In [85]:
#Examining the Objects:

SC = Scalar = np.dot(c, c)
print("Scalar:", SC)

PS = Pseudoscalar = np.dot(c, np.cross(a, b))
print("Pseudoscalar:", PS)

PV = Polarvector = c
print("Polar vector:", PV)

AV = np.cross(a, b)
print("Axial Vector:", AV)

Scalar: 1
Pseudoscalar: 1
Polar vector: [0 0 1]
Axial Vector: [0 0 1]


In [90]:
#Apply inverse (inv) operation...

#...to scalar (np.dot(c, c))...
print("Inverse Operations:")

inv_scalar = np.dot(inv @ c, inv@ c)
print("Scalar",inv_scalar)

inv_pseudoscalar = np.dot(inv @ c, np.cross(inv @a, inv @ b))
print("PS",inv_pseudoscalar)

inv_PV = c
print("PV", inv_PV)

inv_AV = np.cross(inv @ a, inv @ b)
print("AV", inv_AV)



Inverse Operations:
Scalar 1
PS -1
PV [0 0 1]
AV [0 0 1]


In [123]:
#mirZ Operations
print("Mirror_Z Operations:")

mirZ_scalar = np.dot(mirZ @ c, mirZ @ c)
print("Scal",mirZ_scalar)

mirZ_PS = np.dot(mirZ @ c, np.cross(mirZ @ a, mirZ @ b))
print("PS", mirZ_PS)

mirZ_PV = mirZ @ c
print("PV", mirZ_PV)

mirZ_AV = np.cross(mirZ @ a, mirZ @ b)
print("AV", mirZ_AV)


#mirX Operations
print("Mirror_X Operations:")

mirX_scalar = np.dot(mirX @ c, mirX @ c)
print("Scal", mirX_scalar)

mirX_PS = np.dot(mirX @ c, np.cross(mirX @ a, mirX @ b))
print("PS", mirX_PS)

mirX_PV = mirX @ c
print("PV", mirX_PV)

mirX_AV = np.cross(mirX @ a, mirX @ b)
print("AV", mirX_AV)



#rot180
print("Rotation Operations:")

rot180_scalar = np.dot(rot180 @ c, rot180@ c)
print("Scal:", rot180_scalar)

rot180_PS = np.dot(rot180 @ c, np.cross(rot180 @ a, rot180 @ b))
print("PS:", rot180_PS)

rot180_PV = rot180 @ c
print("PV", rot180_PV)

rot180_AV = np.cross(rot180 @ a, rot180 @ b)
print("AV", rot180_PV)


Mirror_Z Operations:
Scal 1
PS 1
PV [0 0 1]
AV [0 0 1]
Mirror_X Operations:
Scal 1
PS 1
PV [ 0  0 -1]
AV [ 0  0 -1]
Rotation Operations:
Scal: 1
PS: 1
PV [ 0  0 -1]
AV [ 0  0 -1]


In [60]:
#Identity

a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
c = np.array([0, 0, 1])

Identity = I = np.array([a, b, c])
print("Identity:", I)


Identity: [[1 0 0]
 [0 1 0]
 [0 0 1]]
