In [73]:
Inversion = Inv = np.array([[-1, 0, 0], [0, -1, 0], [0, 0, -1]])

Mirror_z = MirZ = np.array([[-1, 0, 0], [0, -1, 0], [0, 0, 1]])

Mirror_x = MirX = np.array([[1, 0, 0], [0, -1, 0], [0, 0, -1]])

#Rotation_180

print("Inversion:")
print(Inv)
print("Mirror_Z:")
print(MirZ)
print("Mirror_X:")
print(MirX)

Inversion:
[[-1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
Mirror_Z:
[[-1  0  0]
 [ 0 -1  0]
 [ 0  0  1]]
Mirror_X:
[[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]


In [60]:
#Identity


a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
c = np.array([0, 0, 1])

Identity = I = np.array([a, b, c])
print("Identity:", I)


Identity: [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [66]:
#Defining the Objects:

SC = Scalar = np.dot(c, c)

print("Scalar:", SC)


PS = Pseudoscalar = np.dot(c, np.cross(a, b))

print("Pseudoscalar:", PS)


PV = Pseudovector = c

print("Pseudovector:", PV)


AV = np.cross(a, b)

print("Axial Vector:", AV)

Scalar: 1
Pseudoscalar: 1
Pseudovector: [0 0 1]
Axial Vector: [0 0 1]


In [52]:
#Functions

np.linalg.inv(Identity)



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

| 1D Object | Identity | Inversion | Mirror_z | Mirror_y |
|-----------|----------|-----------|----------|----------|
|Scalar | 1 | Even |
|
|Pseudoscalar | 1 |
|
|Polar Vector | 1 |
|
|Axial Vector | 1 |
